import { useEffect, useMemo, useRef, useState } from "react"
import "./app-next.css"

const STRIKES_WIN = 3
const SERIES_WIN = 2
const LS_NAMES = "strike-zone:names"
const LS_HIST = "strike-zone:history"
const TARGET_MS = 5000

const GAMES = [
  { id: "tap-race", name: "Tap Race", emoji: "👊", type: "sim", rules: "Tap your half as fast as you can. Most taps wins the point." },
  { id: "reaction-duel", name: "Reaction Duel", emoji: "⚡", type: "sim", rules: "Wait for green, then tap first. Tap early and you lose the point." },
  { id: "fakeout-tap", name: "Fakeout Tap", emoji: "🧨", type: "sim", rules: "Only tap when the command says TAP NOW. Fake commands are traps. Tap a trap and you lose the point." },
  { id: "rock-paper-scissors", name: "Rock Paper Scissors", emoji: "✊", type: "pnp", rules: "Pick rock, paper, or scissors, then pass the phone. The second player picks, then both choices are revealed." },
  { id: "stop-the-bar", name: "Stop the Bar", emoji: "🎯", type: "pnp", rules: "Pass the phone. Each player freezes the moving bar. Closest to center wins the point." },
  { id: "color-trap", name: "Color Trap", emoji: "🚦", type: "pnp", rules: "Tap green tiles for +1. Red tiles cost -1. You have 8 seconds. Higher score wins the point." },
  { id: "hold-release", name: "Hold & Release", emoji: "⏱️", type: "pnp", rules: "Hold the button, then release when you think exactly 5 seconds have passed. Closest wins the point." },
  { id: "memory-pattern", name: "Memory Pattern", emoji: "🧠", type: "pnp", rules: "Watch the sequence, then repeat it. Both players get the same pattern. Most correct wins the point." },
  { id: "estimate-time", name: "Estimate Time", emoji: "⌚", type: "pnp", rules: "Tap start, then stop when you think exactly 5 seconds have passed. Closest wins the point." },
]

const RPS = [
  { id: "rock", label: "Rock", emoji: "✊", beats: "scissors" },
  { id: "paper", label: "Paper", emoji: "✋", beats: "rock" },
  { id: "scissors", label: "Scissors", emoji: "✌️", beats: "paper" },
]

const MP_COLORS = ["r", "b", "g", "y"]
const MP_LABELS = { r: "🔴", b: "🔵", g: "🟢", y: "🟡" }
const CONFETTI_COLORS = ["#ff2d6e", "#00e5ff", "#ffd700", "#ff6600", "#cc00ff", "#00ff88"]

function safeParse(value, fallback) { try { return value ? JSON.parse(value) : fallback } catch { return fallback } }
function readStorage(key, fallback) { if (typeof window === "undefined") return fallback; return safeParse(window.localStorage.getItem(key), fallback) }
function writeStorage(key, value) { try { window.localStorage.setItem(key, JSON.stringify(value)) } catch {} }
function formatMs(ms) { return `${(ms / 1000).toFixed(3)}s` }
function diffFromTarget(ms) { const seconds = (ms - TARGET_MS) / 1000; return `${seconds >= 0 ? "+" : ""}${seconds.toFixed(3)}s` }
function chooseLoser(scoreA, scoreB, lowerIsBetter = false) { if (scoreA === scoreB) return Math.random() < 0.5 ? 0 : 1; if (lowerIsBetter) return scoreA < scoreB ? 1 : 0; return scoreA > scoreB ? 1 : 0 }
function pickGame(recent = []) { const excluded = new Set(recent.slice(-2)); const pool = GAMES.filter((game) => !excluded.has(game.id)); const choices = pool.length ? pool : GAMES; return choices[Math.floor(Math.random() * choices.length)] }

function useTimers() {
  const timers = useRef([])
  const addTimeout = (fn, ms) => { const id = window.setTimeout(fn, ms); timers.current.push({ id, type: "timeout" }); return id }
  const addInterval = (fn, ms) => { const id = window.setInterval(fn, ms); timers.current.push({ id, type: "interval" }); return id }
  const clearAll = () => { timers.current.forEach(({ id, type }) => { if (type === "interval") window.clearInterval(id); else window.clearTimeout(id) }); timers.current = [] }
  useEffect(() => clearAll, [])
  return { addTimeout, addInterval, clearAll }
}

function SeriesPips({ value, colorClass }) { return <div className={`series-mini ${colorClass}`}>{Array.from({ length: SERIES_WIN }, (_, i) => <div key={i} className={`series-dot${i < value ? " on" : ""}`} />)}</div> }
function Scoreboard({ players, round, seriesWins, game }) {
  return <div className="sb" aria-label="Scoreboard"><div className="sb-player"><div className="sb-name t-pink">{players[0].name}</div><div className="sb-dots t-pink">{Array.from({ length: STRIKES_WIN }, (_, i) => <div key={i} className={`dot${i < players[0].strikes ? " on" : ""}`} />)}</div>{game && <SeriesPips value={seriesWins[0]} colorClass="t-pink" />}</div><div className="sb-mid bang">ROUND<br />{round}<br />{game ? `${seriesWins[0]}-${seriesWins[1]}` : ""}</div><div className="sb-player"><div className="sb-name t-cyan">{players[1].name}</div><div className="sb-dots t-cyan">{Array.from({ length: STRIKES_WIN }, (_, i) => <div key={i} className={`dot${i < players[1].strikes ? " on" : ""}`} />)}</div>{game && <SeriesPips value={seriesWins[1]} colorClass="t-cyan" />}</div></div>
}

function SetupScreen({ history, onStart }) {
  const savedNames = useMemo(() => readStorage(LS_NAMES, []), [])
  const [names, setNames] = useState([savedNames[0] || "", savedNames[1] || ""])
  const go = () => { const p1 = names[0].trim().slice(0, 16) || "Player 1"; const p2 = names[1].trim().slice(0, 16) || "Player 2"; onStart(p1, p2) }
  return <div className="screen" style={{ justifyContent: "center" }}><div><div className="setup-logo glow-pink t-pink">STRIKE</div><div className="setup-logo glow-cyan t-cyan" style={{ fontSize: 30 }}>ZONE</div><div className="setup-sub" style={{ marginTop: 6 }}>2 players · 1 phone · best 2 of 3</div></div><div className="card" style={{ display: "flex", flexDirection: "column", gap: 12 }}><label className="field"><span className="inp-label">🔴 Player 1</span><input className="inp" placeholder="Enter name" value={names[0]} onChange={(e) => setNames([e.target.value, names[1]])} maxLength={16} /></label><label className="field"><span className="inp-label">🔵 Player 2</span><input className="inp" placeholder="Enter name" value={names[1]} onChange={(e) => setNames([names[0], e.target.value])} maxLength={16} /></label></div><button className="btn btn-go" onClick={go} style={{ fontSize: 36 }}>LET'S GO! 🎮</button>{history.length > 0 && <div className="card" style={{ display: "flex", flexDirection: "column", gap: 6 }}><div className="bang" style={{ fontSize: 16, color: "rgba(255,255,255,.45)", textAlign: "center" }}>RECENT MATCHES</div>{history.slice(0, 3).map((h) => <div key={`${h.date}-${h.winner}-${h.loser}`} style={{ fontSize: 14, color: "rgba(255,255,255,.48)", textAlign: "center" }}>🏆 {h.winner} beat {h.loser} · {h.date}</div>)}</div>}</div>
}

function GameIntroScreen({ game, players, seriesWins, onGo }) {
  return <div className="screen" style={{ justifyContent: "center" }}><div className="gi-emoji">{game.emoji}</div><div className="gi-title bang glow-gold t-gold">{game.name}</div><div className="gi-type">{game.type === "sim" ? "⚔️ simultaneous" : "📱 pass & play"}</div><div className="card gi-rules">{game.rules}</div><div className="card"><div className="series-card"><div><div className="series-name t-pink">{players[0].name}</div><SeriesPips value={seriesWins[0]} colorClass="t-pink" /></div><div><div className="series-score">{seriesWins[0]}-{seriesWins[1]}</div><div className="series-note">First to 2 points gives the other player a strike</div></div><div><div className="series-name t-cyan">{players[1].name}</div><SeriesPips value={seriesWins[1]} colorClass="t-cyan" /></div></div></div>{game.type === "sim" && <div className="card" style={{ display: "flex", justifyContent: "space-between", gap: 12, fontSize: 15, color: "rgba(255,255,255,.58)" }}><span>🔴 {players[0].name} → TOP</span><span>🔵 {players[1].name} → BOTTOM</span></div>}<button className="btn btn-go" onClick={onGo} style={{ fontSize: 36 }}>{seriesWins[0] + seriesWins[1] === 0 ? "START SERIES" : "NEXT POINT"} 🚀</button></div>
}
function PassTo({ name, color, info, onReady }) { return <div className="pass-screen"><div className="pass-icon">📱</div><div className="pass-inst bang">PASS THE PHONE TO</div><div className="pass-name bang" style={{ color }}>{name}</div>{info && <div className="pass-prev">{info}</div>}<button className="btn btn-cyan" style={{ marginTop: 8 }} onClick={onReady}>I'M READY!</button></div> }
function GameRouter({ game, players, onResult }) { const props = { players, onResult }; switch (game.id) { case "tap-race": return <TapRace {...props} />; case "reaction-duel": return <ReactionDuel {...props} />; case "fakeout-tap": return <FakeoutTap {...props} />; case "rock-paper-scissors": return <RockPaperScissors {...props} />; case "stop-the-bar": return <StopTheBar {...props} />; case "color-trap": return <ColorTrap {...props} />; case "hold-release": return <HoldRelease {...props} />; case "memory-pattern": return <MemoryPattern {...props} />; case "estimate-time": return <EstimateTime {...props} />; default: return null } }

function SplitZone({ idx, state, color, top, title, subtitle, name, onTap }) {
  const stateClass = state === "go" ? "zone-go" : state === "early" ? "zone-early" : state === "won" ? "zone-won" : state === "lost" ? "zone-lost" : "zone-wait"
  const textColor = state === "go" || state === "won" ? "#00e5ff" : state === "early" || state === "lost" ? "#ff4444" : "rgba(255,255,255,.54)"
  return <div className={`split-zone ${top ? "top" : ""} ${color} ${stateClass}`} onPointerDown={(e) => { e.preventDefault(); onTap(idx) }}><div className="command-text" style={{ color: textColor }}>{title}</div><div className="command-sub">{subtitle}</div><div className="bang" style={{ fontSize: 18, color: "rgba(255,255,255,.42)" }}>{name}</div></div>
}

function TapRace({ players, onResult }) {
  const [countdown, setCountdown] = useState(3), [counts, setCounts] = useState([0, 0]), [timeLeft, setTimeLeft] = useState(7), [done, setDone] = useState(false)
  const countsRef = useRef([0, 0]), doneRef = useRef(false), { addTimeout, addInterval } = useTimers()
  useEffect(() => { addTimeout(() => setCountdown(2), 900); addTimeout(() => setCountdown(1), 1800); addTimeout(() => setCountdown(0), 2700); addTimeout(() => { setCountdown(-1); let remaining = 7; const intervalId = addInterval(() => { remaining -= 1; setTimeLeft(remaining); if (remaining <= 0 && !doneRef.current) { window.clearInterval(intervalId); doneRef.current = true; setDone(true); const loser = chooseLoser(countsRef.current[0], countsRef.current[1]); addTimeout(() => onResult(loser), 1200) } }, 1000) }, 3300) }, [])
  const tap = (idx) => { if (countdown !== -1 || doneRef.current) return; const next = [...countsRef.current]; next[idx] += 1; countsRef.current = next; setCounts(next) }
  return <div className="split-outer">{countdown >= 0 && <div className="cd-overlay"><div key={countdown} className="cd-num" style={{ color: countdown === 0 ? "#00e5ff" : countdown === 1 ? "#ff2d6e" : "#ffd700" }}>{countdown === 0 ? "GO!" : countdown}</div></div>}<div className="split-zone top pink" onPointerDown={(e) => { e.preventDefault(); tap(0) }}><div className="big-count t-pink">{counts[0]}</div><div className="player-label t-pink">{players[0].name}</div></div><div className="split-mid"><div className="bang" style={{ fontSize: 26, color: timeLeft <= 3 ? "#ff2d6e" : "#fff" }}>{countdown === -1 && !done ? `${timeLeft}s` : done ? "TIME!" : ""}</div></div><div className="split-zone cyan" onPointerDown={(e) => { e.preventDefault(); tap(1) }}><div className="big-count t-cyan">{counts[1]}</div><div className="player-label t-cyan">{players[1].name}</div></div>{done && <div className="cd-overlay"><div className="bang glow-gold t-gold" style={{ fontSize: 64 }}>TIME!</div><div className="bang" style={{ fontSize: 24, color: "rgba(255,255,255,.72)", marginTop: 8 }}>{players[0].name} {counts[0]} vs {counts[1]} {players[1].name}</div></div>}</div>
}

function ReactionDuel({ players, onResult }) {
  const [zones, setZones] = useState(["wait", "wait"]), doneRef = useRef(false), phaseRef = useRef("wait"), { addTimeout, clearAll } = useTimers()
  useEffect(() => { addTimeout(() => { if (doneRef.current) return; phaseRef.current = "go"; setZones(["go", "go"]); addTimeout(() => { if (doneRef.current) return; doneRef.current = true; const loser = Math.random() < 0.5 ? 0 : 1; setZones((old) => old.map((_, i) => (i === loser ? "lost" : "won"))); addTimeout(() => onResult(loser), 950) }, 4000) }, 1500 + Math.random() * 2500) }, [])
  const handleTap = (idx) => { if (doneRef.current) return; clearAll(); doneRef.current = true; if (phaseRef.current === "wait") { setZones((old) => old.map((_, i) => (i === idx ? "early" : "won"))); addTimeout(() => onResult(idx), 1100) } else { const loser = 1 - idx; setZones((old) => old.map((_, i) => (i === idx ? "won" : "lost"))); addTimeout(() => onResult(loser), 950) } }
  const status = (state) => state === "wait" ? ["WAIT...", "Don't tap yet!"] : state === "go" ? ["TAP NOW!", "GO GO GO!"] : state === "early" ? ["TOO EARLY!", "False start 💀"] : state === "won" ? ["YOU WIN!", "⚡ Fast reflexes!"] : ["YOU LOSE!", "Too slow 😬"]
  return <div className="split-outer">{[0, 1].map((idx) => { const [main, sub] = status(zones[idx]); return <SplitZone key={idx} idx={idx} state={zones[idx]} color={idx === 0 ? "pink" : "cyan"} top={idx === 0} title={main} subtitle={sub} name={players[idx].name} onTap={handleTap} /> })}</div>
}

function FakeoutTap({ players, onResult }) {
  const fakeCommands = ["DON'T TAP", "WAIT!", "NOT YET", "HOLD", "FREEZE", "NOPE"]
  const [command, setCommand] = useState({ text: "GET READY", kind: "wait" }), [zones, setZones] = useState(["wait", "wait"]), [step, setStep] = useState(0)
  const doneRef = useRef(false), commandRef = useRef("wait"), { addTimeout, clearAll } = useTimers()
  useEffect(() => { const fakeCount = 2 + Math.floor(Math.random() * 4); let delay = 800; for (let i = 0; i < fakeCount; i += 1) { addTimeout(() => { if (doneRef.current) return; const text = fakeCommands[Math.floor(Math.random() * fakeCommands.length)]; commandRef.current = "fake"; setCommand({ text, kind: "fake" }); setZones(["wait", "wait"]); setStep((value) => value + 1) }, delay); delay += 850 + Math.random() * 450 } addTimeout(() => { if (doneRef.current) return; commandRef.current = "go"; setCommand({ text: "TAP NOW!", kind: "go" }); setZones(["go", "go"]); addTimeout(() => { if (doneRef.current) return; doneRef.current = true; const loser = Math.random() < 0.5 ? 0 : 1; setZones((old) => old.map((_, i) => (i === loser ? "lost" : "won"))); addTimeout(() => onResult(loser), 950) }, 2600) }, delay) }, [])
  const handleTap = (idx) => { if (doneRef.current) return; clearAll(); doneRef.current = true; if (commandRef.current === "go") { const loser = 1 - idx; setZones((old) => old.map((_, i) => (i === idx ? "won" : "lost"))); addTimeout(() => onResult(loser), 900); return } setZones((old) => old.map((_, i) => (i === idx ? "early" : "won"))); addTimeout(() => onResult(idx), 1100) }
  const subtitle = command.kind === "go" ? "Real command — tap fast!" : command.kind === "fake" ? "Trap command — don't tap" : "Watch the command"
  return <div className="split-outer"><div className="cd-overlay" style={{ pointerEvents: "none", background: "rgba(8,8,26,.15)", zIndex: 2 }}><div key={`${command.text}-${step}`} className="cd-num" style={{ fontSize: command.kind === "go" ? 96 : 58, color: command.kind === "go" ? "#00ff44" : command.kind === "fake" ? "#ff2d6e" : "#ffd700" }}>{command.text}</div><div className="bang" style={{ fontSize: 18, color: "rgba(255,255,255,.58)" }}>{subtitle}</div></div>{[0, 1].map((idx) => <SplitZone key={idx} idx={idx} state={zones[idx]} color={idx === 0 ? "pink" : "cyan"} top={idx === 0} title={zones[idx] === "won" ? "YOU WIN!" : zones[idx] === "lost" ? "YOU LOSE!" : zones[idx] === "early" ? "FAKEOUT!" : players[idx].name} subtitle={zones[idx] === "early" ? "Tapped the trap" : ""} name="" onTap={handleTap} />)}</div>
}

function RockPaperScissors({ players, onResult }) {
  const [phase, setPhase] = useState("p0"), [choices, setChoices] = useState([null, null]), [message, setMessage] = useState("Pick secretly. No peeking."), { addTimeout } = useTimers()
  const pick = (player, choice) => { const next = [...choices]; next[player] = choice; setChoices(next); if (player === 0) { setMessage(`${players[0].name} locked in. Pass the phone.`); setPhase("handoff"); return } const [p0, p1] = next; if (p0.id === p1.id) { setMessage("Tie! Replay this point."); setPhase("tie"); addTimeout(() => { setChoices([null, null]); setMessage("Pick secretly. No peeking."); setPhase("p0") }, 1500); return } const p0Wins = p0.beats === p1.id; const loser = p0Wins ? 1 : 0; setMessage(`${players[1 - loser].name} wins the point!`); setPhase("reveal"); addTimeout(() => onResult(loser), 1400) }
  const ChoiceButtons = ({ player }) => <div className="choice-grid">{RPS.map((choice) => <button key={choice.id} className="choice-btn" onClick={() => pick(player, choice)}><span className="choice-emoji">{choice.emoji}</span><span>{choice.label}</span></button>)}</div>
  if (phase === "handoff") return <PassTo name={players[1].name} color="#00e5ff" info="Player 1 picked. Choose your move without looking back." onReady={() => setPhase("p1")} />
  if (phase === "reveal" || phase === "tie") return <div className="mini-outer"><div className="bang t-gold" style={{ fontSize: 34 }}>{message}</div><div className="reveal-row">{[0, 1].map((idx) => <div key={idx} className="reveal-card"><div className="emoji">{choices[idx]?.emoji ?? "❔"}</div><div className={`name ${idx === 0 ? "t-pink" : "t-cyan"}`}>{players[idx].name}</div><div className="command-sub">{choices[idx]?.label ?? "Hidden"}</div></div>)}</div></div>
  const player = phase === "p0" ? 0 : 1
  return <div className="mini-outer"><div className="bang" style={{ fontSize: 34, color: player === 0 ? "#ff2d6e" : "#00e5ff" }}>{players[player].name}</div><div className="command-sub">{message}</div><ChoiceButtons player={player} /></div>
}

function StopTheBar({ players, onResult }) {
  const [phase, setPhase] = useState("p0-ready"), [scores, setScores] = useState([null, null]); const barRef = useRef(null), centerRef = useRef(20), dirRef = useRef(1), rafRef = useRef(null), activeRef = useRef(false), lastTimeRef = useRef(null)
  const stopBar = () => { activeRef.current = false; if (rafRef.current) window.cancelAnimationFrame(rafRef.current) }
  const startBar = () => { centerRef.current = 18 + Math.random() * 18; dirRef.current = 1; activeRef.current = true; lastTimeRef.current = null; const animate = (now) => { if (!activeRef.current) return; if (lastTimeRef.current === null) lastTimeRef.current = now; const dt = Math.min((now - lastTimeRef.current) / 1000, 0.05); lastTimeRef.current = now; centerRef.current += dirRef.current * 62 * dt; if (centerRef.current >= 96) { centerRef.current = 96; dirRef.current = -1 } if (centerRef.current <= 4) { centerRef.current = 4; dirRef.current = 1 } if (barRef.current) barRef.current.style.left = `${centerRef.current}%`; rafRef.current = window.requestAnimationFrame(animate) }; rafRef.current = window.requestAnimationFrame(animate) }
  useEffect(() => () => stopBar(), [])
  const startPhase = (next) => { setPhase(next); window.setTimeout(startBar, 80) }
  const handleTap = () => { if (phase !== "p0-playing" && phase !== "p1-playing") return; stopBar(); const dist = Math.abs(centerRef.current - 50); if (phase === "p0-playing") { setScores([dist, null]); setPhase("handoff") } else { const s0 = scores[0]; setScores([s0, dist]); setPhase("done"); window.setTimeout(() => onResult(chooseLoser(s0, dist, true)), 1200) } }
  const accuracy = (dist) => `${Math.max(0, Math.min(100, 100 - dist * 2)).toFixed(0)}% accuracy`
  if (phase === "p0-ready") return <div className="mini-outer"><div className="bang t-pink" style={{ fontSize: 32 }}>{players[0].name}<br />YOU'RE UP FIRST</div><div className="command-sub">Stop the bar as close to the golden line as possible.</div><button className="btn btn-go" onClick={() => startPhase("p0-playing")}>START!</button></div>
  if (phase === "handoff") return <PassTo name={players[1].name} color="#00e5ff" info={`${players[0].name}: ${accuracy(scores[0])} — can you beat it?`} onReady={() => startPhase("p1-playing")} />
  if (phase === "done") return <div className="mini-outer"><div className="bang t-gold" style={{ fontSize: 40 }}>RESULTS!</div><div className="score-row"><div><span className="t-pink">{players[0].name}</span><br />{accuracy(scores[0])}</div><div><span className="t-cyan">{players[1].name}</span><br />{accuracy(scores[1])}</div></div><div className="command-sub">Closest to center wins this point.</div></div>
  const player = phase.startsWith("p0") ? 0 : 1
  return <div className="mini-outer" onPointerDown={(e) => { e.preventDefault(); handleTap() }} style={{ touchAction: "none" }}><div className="bang" style={{ fontSize: 32, color: player === 0 ? "#ff2d6e" : "#00e5ff" }}>{players[player].name}<br />TAP TO STOP!</div><div className="track-wrap"><div className="track"><div className="target-zone" /><div className="target-line" /><div className="bar" ref={barRef} style={{ left: `${centerRef.current}%` }} /></div></div><div className="command-sub">🎯 Freeze the bar on the center line.</div>{scores[0] !== null && <div className="command-sub" style={{ color: "#ffd700" }}>{players[0].name}: {accuracy(scores[0])}</div>}</div>
}

function ColorTrap({ players, onResult }) {
  const [phase, setPhase] = useState("p0-ready"), [cells, setCells] = useState(["neutral", "neutral", "neutral", "neutral"]), [timeLeft, setTimeLeft] = useState(8), [scoreDisplay, setScoreDisplay] = useState(0), [scores, setScores] = useState([null, null]); const cellsRef = useRef(cells), scoreRef = useRef(0), activeRef = useRef(false), { addInterval, clearAll, addTimeout } = useTimers()
  const randomize = () => { const values = ["green", "green", "red", "neutral"]; for (let i = values.length - 1; i > 0; i -= 1) { const j = Math.floor(Math.random() * (i + 1)); [values[i], values[j]] = [values[j], values[i]] } cellsRef.current = values; setCells(values) }
  const startTurn = (player) => { clearAll(); activeRef.current = true; scoreRef.current = 0; setScoreDisplay(0); setTimeLeft(8); randomize(); addInterval(randomize, 700); let remaining = 8; addInterval(() => { remaining -= 1; setTimeLeft(remaining); if (remaining <= 0) { activeRef.current = false; clearAll(); const finalScore = scoreRef.current; setScores((prev) => { const next = [...prev]; next[player] = finalScore; return next }); setPhase(player === 0 ? "handoff" : "done") } }, 1000) }
  useEffect(() => { if (phase !== "done") return undefined; const [s0, s1] = scores; if (s0 == null || s1 == null) return undefined; addTimeout(() => onResult(chooseLoser(s0, s1)), 1100); return undefined }, [phase, scores])
  const handleCellTap = (idx) => { if (!activeRef.current) return; const type = cellsRef.current[idx]; if (type === "neutral") return; scoreRef.current += type === "green" ? 1 : -1; const next = [...cellsRef.current]; next[idx] = "neutral"; cellsRef.current = next; setCells(next); setScoreDisplay(scoreRef.current) }
  if (phase === "p0-ready") return <PassTo name={players[0].name} color="#ff2d6e" info="Tap GREEN = +1 · Tap RED = -1 · 8 seconds." onReady={() => { setPhase("p0-play"); startTurn(0) }} />
  if (phase === "handoff") return <PassTo name={players[1].name} color="#00e5ff" info={`${players[0].name} scored ${scores[0]} — beat it.`} onReady={() => { setPhase("p1-play"); startTurn(1) }} />
  if (phase === "done") return <div className="ct-outer" style={{ alignItems: "center", justifyContent: "center" }}><div className="bang t-gold glow-gold" style={{ fontSize: 48 }}>RESULTS!</div><div className="bang" style={{ fontSize: 28, display: "flex", gap: 24, flexWrap: "wrap", justifyContent: "center" }}><div className="t-pink">{players[0].name}: {scores[0]}</div><div className="t-cyan">{players[1].name}: {scores[1]}</div></div><div className="bang" style={{ fontSize: 20, color: "rgba(255,255,255,.45)" }}>Higher score wins this point.</div></div>
  const player = phase.includes("p0") ? 0 : 1; const cellEmoji = (type) => type === "green" ? "✅" : type === "red" ? "❌" : "·"
  return <div className="ct-outer"><div className="ct-header"><div className="ct-score" style={{ color: scoreDisplay >= 0 ? "#00ff44" : "#ff4444" }}>{scoreDisplay >= 0 ? "+" : ""}{scoreDisplay}</div><div className="ct-turn" style={{ color: player === 0 ? "#ff2d6e" : "#00e5ff" }}>{players[player].name}</div><div className="ct-time" style={{ color: timeLeft <= 3 ? "#ff2d6e" : "#fff" }}>{timeLeft}s</div></div><div className="grid-2x2">{cells.map((type, idx) => <div key={idx} className={`ct-cell ${type}`} onPointerDown={(e) => { e.preventDefault(); handleCellTap(idx) }}>{cellEmoji(type)}</div>)}</div></div>
}

function HoldRelease({ players, onResult }) {
  const [phase, setPhase] = useState("p0-ready"), [holding, setHolding] = useState(false), [elapsed, setElapsed] = useState([null, null]), startTimeRef = useRef(null)
  const playerFromPhase = () => phase.includes("p0") ? 0 : 1
  const handleDown = () => { if (!phase.endsWith("hold")) return; startTimeRef.current = performance.now(); setHolding(true) }
  const handleUp = () => { if (!holding || startTimeRef.current == null) return; const player = playerFromPhase(); const ms = performance.now() - startTimeRef.current; startTimeRef.current = null; setHolding(false); setElapsed((prev) => { const next = [...prev]; next[player] = ms; return next }); setPhase(player === 0 ? "p0-done" : "p1-done") }
  useEffect(() => { if (phase === "p0-done") { const id = window.setTimeout(() => setPhase("handoff"), 1400); return () => window.clearTimeout(id) } if (phase === "p1-done") { const id = window.setTimeout(() => setPhase("done"), 1400); return () => window.clearTimeout(id) } if (phase === "done") { const [e0, e1] = elapsed; if (e0 == null || e1 == null) return undefined; const d0 = Math.abs(e0 - TARGET_MS), d1 = Math.abs(e1 - TARGET_MS); const id = window.setTimeout(() => onResult(chooseLoser(d0, d1, true)), 1100); return () => window.clearTimeout(id) } return undefined }, [phase, elapsed])
  if (phase === "p0-ready") return <PassTo name={players[0].name} color="#ff2d6e" info="Hold the button. Release at exactly 5 seconds." onReady={() => setPhase("p0-hold")} />
  if (phase === "handoff") return <PassTo name={players[1].name} color="#00e5ff" info={`${players[0].name}: ${formatMs(elapsed[0])} (${diffFromTarget(elapsed[0])}) — beat it.`} onReady={() => setPhase("p1-hold")} />
  if (phase === "done") return <TimedResults className="mini-outer" players={players} elapsed={elapsed} />
  const player = playerFromPhase(), isDone = phase.endsWith("done"), doneElapsed = elapsed[player]
  return <div className="mini-outer"><div className="bang" style={{ fontSize: 32, color: player === 0 ? "#ff2d6e" : "#00e5ff" }}>{players[player].name}</div><div className="command-sub">🎯 Target: exactly 5.000 seconds</div><button className={`circle-btn ${holding ? "holding" : "idle"}`} onPointerDown={(e) => { e.preventDefault(); handleDown() }} onPointerUp={handleUp} onPointerCancel={handleUp} onPointerLeave={handleUp}>{holding ? "HOLDING..." : isDone ? "✓" : "HOLD"}</button>{isDone && doneElapsed !== null && <div className="result-big">{formatMs(doneElapsed)}<br /><span style={{ color: "rgba(255,255,255,.5)", fontSize: 18 }}>{diffFromTarget(doneElapsed)} from target</span></div>}</div>
}

function MemoryPattern({ players, onResult }) {
  const [sequence] = useState(() => Array.from({ length: 5 }, () => MP_COLORS[Math.floor(Math.random() * 4)])), [phase, setPhase] = useState("show-p0"), [litCell, setLitCell] = useState(null), [inputProgress, setInputProgress] = useState([]), [scores, setScores] = useState([null, null]), [status, setStatus] = useState(""); const inputRef = useRef([]), { addTimeout, clearAll } = useTimers()
  useEffect(() => { if (phase !== "show-p0" && phase !== "show-p1") return undefined; clearAll(); inputRef.current = []; setInputProgress([]); setLitCell(null); const player = phase === "show-p0" ? 0 : 1; setStatus(`Watch the sequence, ${players[player].name}!`); let delay = 550; sequence.forEach((color) => { addTimeout(() => setLitCell(color), delay); delay += 640; addTimeout(() => setLitCell(null), delay); delay += 260 }); addTimeout(() => { setStatus("Repeat the sequence!"); setPhase(phase === "show-p0" ? "input-p0" : "input-p1") }, delay + 160); return undefined }, [phase])
  const finishTurn = (player, score, message) => { setStatus(message); setScores((prev) => { const next = [...prev]; next[player] = score; return next }); inputRef.current = []; addTimeout(() => setPhase(player === 0 ? "handoff" : "done"), 800) }
  const handleCellTap = (color) => { const isP0 = phase === "input-p0", isP1 = phase === "input-p1"; if (!isP0 && !isP1) return; const player = isP0 ? 0 : 1; const idx = inputRef.current.length; const nextInput = [...inputRef.current, color]; inputRef.current = nextInput; setInputProgress(nextInput); if (color !== sequence[idx]) { finishTurn(player, idx, `Wrong! ${idx}/${sequence.length} correct`); return } if (nextInput.length === sequence.length) { finishTurn(player, sequence.length, "PERFECT! 🎉"); return } setStatus(`${nextInput.length}/${sequence.length} ✓`) }
  useEffect(() => { if (phase !== "done") return undefined; const [s0, s1] = scores; if (s0 == null || s1 == null) return undefined; addTimeout(() => onResult(chooseLoser(s0, s1)), 1300); return undefined }, [phase, scores])
  if (phase === "handoff") return <PassTo name={players[1].name} color="#00e5ff" info={`${players[0].name} got ${scores[0]}/${sequence.length}. Same sequence.`} onReady={() => setPhase("show-p1")} />
  if (phase === "done") return <div className="mp-outer" style={{ alignItems: "center", justifyContent: "center", gap: 16 }}><div className="bang t-gold glow-gold" style={{ fontSize: 40 }}>RESULTS!</div><div className="bang" style={{ fontSize: 24, display: "flex", gap: 20, flexWrap: "wrap", justifyContent: "center" }}><div className="t-pink">{players[0].name}: {scores[0]}/{sequence.length}</div><div className="t-cyan">{players[1].name}: {scores[1]}/{sequence.length}</div></div><div className="bang" style={{ color: "rgba(255,255,255,.5)", fontSize: 16 }}>Sequence: {sequence.map((c) => MP_LABELS[c]).join(" ")}</div></div>
  const isInput = phase === "input-p0" || phase === "input-p1", player = phase.includes("p0") ? 0 : 1
  return <div className="mp-outer"><div className="mp-status" style={{ color: player === 0 ? "#ff2d6e" : "#00e5ff" }}>{status}</div>{isInput && <div className="mp-progress">{inputProgress.map((c) => MP_LABELS[c]).join(" ")} <span style={{ color: "rgba(255,255,255,.28)" }}>{"·".repeat(Math.max(0, sequence.length - inputProgress.length))}</span></div>}<div className="grid-2x2">{MP_COLORS.map((color) => <div key={color} className={`mp-cell ${color}${isInput ? " on" : ""}${litCell === color ? " lit" : ""}`} onPointerDown={(e) => { e.preventDefault(); if (isInput) handleCellTap(color) }} />)}</div></div>
}

function EstimateTime({ players, onResult }) {
  const [phase, setPhase] = useState("p0-ready"), [elapsed, setElapsed] = useState([null, null]), [running, setRunning] = useState(false), startRef = useRef(null)
  const playerFromPhase = () => phase.startsWith("p0") ? 0 : 1
  const handleTap = () => { const player = playerFromPhase(); if (!running) { startRef.current = performance.now(); setRunning(true); setPhase(`p${player}-run`); return } const ms = performance.now() - startRef.current; startRef.current = null; setRunning(false); setElapsed((prev) => { const next = [...prev]; next[player] = ms; return next }); setPhase(player === 0 ? "p0-done" : "p1-done") }
  useEffect(() => { if (phase === "p0-done") { const id = window.setTimeout(() => setPhase("handoff"), 1400); return () => window.clearTimeout(id) } if (phase === "p1-done") { const id = window.setTimeout(() => setPhase("done"), 1400); return () => window.clearTimeout(id) } if (phase === "done") { const [e0, e1] = elapsed; if (e0 == null || e1 == null) return undefined; const d0 = Math.abs(e0 - TARGET_MS), d1 = Math.abs(e1 - TARGET_MS); const id = window.setTimeout(() => onResult(chooseLoser(d0, d1, true)), 1100); return () => window.clearTimeout(id) } return undefined }, [phase, elapsed])
  if (phase === "p0-ready") return <PassTo name={players[0].name} color="#ff2d6e" info="Tap START, then STOP when you think 5 seconds passed." onReady={() => setPhase("p0-run")} />
  if (phase === "handoff") return <PassTo name={players[1].name} color="#00e5ff" info={`${players[0].name}: ${formatMs(elapsed[0])} (${diffFromTarget(elapsed[0])}) — beat it.`} onReady={() => setPhase("p1-run")} />
  if (phase === "done") return <TimedResults className="mini-outer" players={players} elapsed={elapsed} />
  const player = playerFromPhase(), isDone = phase.endsWith("done"), doneElapsed = elapsed[player]
  return <div className="mini-outer"><div className="bang" style={{ fontSize: 32, color: player === 0 ? "#ff2d6e" : "#00e5ff" }}>{players[player].name}</div><div className="command-sub">🎯 Stop as close to 5.000s as possible</div><button className={`circle-btn ${running ? "stop" : "start"}`} onPointerDown={(e) => { e.preventDefault(); if (!isDone) handleTap() }}>{isDone ? "✓" : running ? "STOP!" : "START"}</button>{running && <div className="bang t-gold" style={{ fontSize: 22 }}>⏱️ Counting in your head...</div>}{isDone && doneElapsed !== null && <div className="result-big">{formatMs(doneElapsed)}<br /><span style={{ color: "rgba(255,255,255,.5)", fontSize: 18 }}>{diffFromTarget(doneElapsed)} from target</span></div>}</div>
}
function TimedResults({ className, players, elapsed }) { return <div className={className}><div className="bang t-gold glow-gold" style={{ fontSize: 40 }}>RESULTS!</div><div className="bang" style={{ fontSize: 22, display: "flex", flexDirection: "column", gap: 10, textAlign: "center" }}><div><span className="t-pink">{players[0].name}:</span> {formatMs(elapsed[0])} ({diffFromTarget(elapsed[0])})</div><div><span className="t-cyan">{players[1].name}:</span> {formatMs(elapsed[1])} ({diffFromTarget(elapsed[1])})</div></div><div style={{ color: "rgba(255,255,255,.5)", fontFamily: "Bangers,cursive", fontSize: 18 }}>Target: 5.000s</div></div> }
function PointScreen({ players, pointResult, onNextPoint }) { const { pointWinnerIdx, seriesWins, gameName } = pointResult; return <div className="point-screen"><div className="ps-label">POINT WINNER</div><div className={`ps-name ${pointWinnerIdx === 0 ? "t-pink" : "t-cyan"}`}>{players[pointWinnerIdx].name}</div><div className="ps-score">{seriesWins[0]}-{seriesWins[1]}</div><div className="series-note">{gameName} is best 2 out of 3. First to 2 gives the other player a strike.</div><button className="btn btn-cyan" onClick={onNextPoint} style={{ marginTop: 12 }}>NEXT POINT →</button></div> }
function ResultScreen({ players, result, onNext }) { const { loserIdx, newStrikes, seriesWinnerIdx, gameName } = result, eliminated = newStrikes >= STRIKES_WIN; return <div className="result-screen">{eliminated ? <><div className="rs-label">GAME OVER!</div><div className="rs-name t-pink glow-pink">{players[loserIdx].name}</div><div className="rs-elim">ELIMINATED! ☠️</div><div className="rs-dots">{Array.from({ length: STRIKES_WIN }, (_, i) => <div key={i} className="rs-dot on" />)}</div><div className="rs-winner">🏆 {players[seriesWinnerIdx].name} won {gameName} 2 out of 3 and wins the match!</div><button className="btn btn-gold" onClick={onNext} style={{ marginTop: 12 }}>SEE THE WINNER! 🎉</button></> : <><div className="rs-label">SERIES LOST</div><div className="rs-strike">STRIKE!</div><div className="rs-name t-pink">{players[loserIdx].name}</div><div className="rs-dots">{Array.from({ length: STRIKES_WIN }, (_, i) => <div key={i} className={`rs-dot${i < newStrikes ? " on" : ""}`} />)}</div><div className="rs-winner" style={{ marginTop: 4 }}>{players[seriesWinnerIdx].name} won {gameName} 2 out of 3</div><button className="btn btn-cyan" onClick={onNext} style={{ marginTop: 12 }}>NEXT ROUND →</button></>}</div> }
function FinalScreen({ players, history, onRestart }) { const winner = players.find((p) => p.strikes < STRIKES_WIN), loser = players.find((p) => p.strikes >= STRIKES_WIN); const confetti = useMemo(() => Array.from({ length: 64 }, (_, i) => ({ id: i, left: Math.random() * 100, dur: 2.2 + Math.random() * 2.8, delay: Math.random() * 2.5, color: CONFETTI_COLORS[i % CONFETTI_COLORS.length], w: 7 + Math.random() * 9, h: 7 + Math.random() * 9, rot: Math.random() * 360 })), []); return <div className="final-screen"><div className="confetti">{confetti.map((p) => <div key={p.id} className="cp" style={{ left: `${p.left}%`, background: p.color, width: `${p.w}px`, height: `${p.h}px`, transform: `rotate(${p.rot}deg)`, animationDuration: `${p.dur}s`, animationDelay: `${p.delay}s` }} />)}</div><div className="fs-crown">👑</div><div className="fs-wins bang">CHAMPION!</div><div className="fs-winner glow-gold t-gold">{winner?.name}</div><div style={{ fontSize: 16, color: "rgba(255,255,255,.48)", letterSpacing: 1 }}>{loser?.name} got 3 strikes and is out.</div>{history.length > 0 && <div className="card" style={{ display: "flex", flexDirection: "column", gap: 6, width: "100%", maxWidth: 320, marginTop: 8 }}><div className="bang" style={{ fontSize: 16, color: "rgba(255,255,255,.45)", textAlign: "center" }}>MATCH HISTORY</div>{history.slice(0, 4).map((h) => <div key={`${h.date}-${h.winner}-${h.loser}`} className="fs-hist">🏆 {h.winner} beat {h.loser} · {h.date}</div>)}</div>}<button className="btn btn-go" onClick={onRestart} style={{ marginTop: 12, fontSize: 26 }}>PLAY AGAIN! 🎮</button></div> }

export default function AppNext() {
  const [screen, setScreen] = useState("setup"), [players, setPlayers] = useState([{ name: "Player 1", strikes: 0 }, { name: "Player 2", strikes: 0 }]), [game, setGame] = useState(null), [result, setResult] = useState(null), [pointResult, setPointResult] = useState(null), [seriesWins, setSeriesWins] = useState([0, 0]), [recentIds, setRecentIds] = useState([]), [round, setRound] = useState(1), [history, setHistory] = useState(() => readStorage(LS_HIST, []))
  const startMatch = (p1, p2) => { writeStorage(LS_NAMES, [p1, p2]); const nextGame = pickGame([]); setPlayers([{ name: p1, strikes: 0 }, { name: p2, strikes: 0 }]); setRound(1); setRecentIds([nextGame.id]); setGame(nextGame); setSeriesWins([0, 0]); setPointResult(null); setResult(null); setScreen("intro") }
  const handleGamePoint = (pointLoserIdx) => { const pointWinnerIdx = 1 - pointLoserIdx; const nextSeries = [...seriesWins]; nextSeries[pointWinnerIdx] += 1; if (nextSeries[pointWinnerIdx] < SERIES_WIN) { setSeriesWins(nextSeries); setPointResult({ pointWinnerIdx, pointLoserIdx, seriesWins: nextSeries, gameName: game.name }); setScreen("point"); return } const seriesLoserIdx = 1 - pointWinnerIdx; setSeriesWins([0, 0]); setPointResult(null); setPlayers((currentPlayers) => { const newStrikes = currentPlayers[seriesLoserIdx].strikes + 1; const nextPlayers = currentPlayers.map((player, idx) => idx === seriesLoserIdx ? { ...player, strikes: newStrikes } : player); setResult({ loserIdx: seriesLoserIdx, newStrikes, seriesWinnerIdx: pointWinnerIdx, gameName: game.name }); if (newStrikes >= STRIKES_WIN) { const entry = { winner: nextPlayers[pointWinnerIdx].name, loser: nextPlayers[seriesLoserIdx].name, date: new Date().toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) }; setHistory((prev) => { const nextHistory = [entry, ...prev].slice(0, 10); writeStorage(LS_HIST, nextHistory); return nextHistory }) } return nextPlayers }); setScreen("result") }
  const handleNextPoint = () => { setPointResult(null); setScreen("intro") }
  const handleNextRound = () => { if (result?.newStrikes >= STRIKES_WIN) { setScreen("final"); return } const nextGame = pickGame(recentIds); setRecentIds((prev) => [...prev, nextGame.id].slice(-6)); setGame(nextGame); setRound((currentRound) => currentRound + 1); setSeriesWins([0, 0]); setPointResult(null); setResult(null); setScreen("intro") }
  const handleRestart = () => { setScreen("setup"); setPlayers([{ name: "Player 1", strikes: 0 }, { name: "Player 2", strikes: 0 }]); setResult(null); setPointResult(null); setSeriesWins([0, 0]); setRecentIds([]); setRound(1); setGame(null) }
  const showScoreboard = screen === "game" || screen === "point" || screen === "result"
  return <div className="app">{showScoreboard && <Scoreboard players={players} round={round} seriesWins={seriesWins} game={game} />}{screen === "setup" && <SetupScreen history={history} onStart={startMatch} />}{screen === "intro" && game && <GameIntroScreen game={game} players={players} seriesWins={seriesWins} onGo={() => setScreen("game")} />}{screen === "game" && game && <GameRouter game={game} players={players} onResult={handleGamePoint} />}{screen === "point" && pointResult && <PointScreen players={players} pointResult={pointResult} onNextPoint={handleNextPoint} />}{screen === "result" && result && <ResultScreen players={players} result={result} onNext={handleNextRound} />}{screen === "final" && <FinalScreen players={players} history={history} onRestart={handleRestart} />}</div>
}
